MONGODB_HOST: mongodb-{{ env }}.daws90s.fun
REDIS_HOST: redis-{{ env }}.daws90s.fun
MYSQL_HOST: mysql-{{ env }}.daws90s.fun 
RABBITMQ_HOST: rabbitmq-{{ env }}.daws90s.fun 
CATALOGUE_HOST: catalogue-{{ env }}.daws90s.fun
USER_HOST: user-{{ env }}.daws90s.fun
CART_HOST: cart-{{ env }}.daws90s.fun
SHIPPING_HOST: shipping-{{ env }}.daws90s.fun
PAYMENT_HOST: payment-{{ env }}.daws90s.fun




